apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: ingress-nginx
spec:
  type: ExternalName
  externalName: jenkins-service.jenkins.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: block-buster-service
  namespace: ingress-nginx
spec:
  type: ExternalName
  externalName: block-buster-service.1-demo.svc.cluster.local
