apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: jenkins
spec:
  interval: 1m0s
  path: ./monitoring/controllers/kube-prometheus-stacked
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-monitoring
  timeout: 5m0s
  wait: true
